annotations:
  - checks:
      - fuzzing
    reasons:
      - reason: not-applicable # Erlang / Elixir is memory safe
  - checks:
      - packaging
    reasons:
      - reason: not-supported # Using Hex.pm
