%% @private
%% This file is generated by `rebar3 purl_gen` from the purl-spec type
%% definitions in `priv/spec/types/*.json`.
%%
%% Do not edit it by hand. Run `rebar3 purl_gen` after updating the
%% `priv/spec` submodule and commit the result.
%%
%% purl-spec revision: 995f3878f5bb6979bc6560cd747e422e8262f18b
-module(purl_type_data).

-moduledoc false.

-export([specifications/0]).

-spec specifications() -> [purl:type_specification()].
specifications() ->
    [
        #{
            '$id' => <<"https://packageurl.org/types/alpm-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description =>
                <<"Arch Linux packages and other users of the libalpm/pacman package manager.">>,
            examples =>
                [
                    <<"pkg:alpm/arch/pacman@6.0.1-1?arch=x86_64">>,
                    <<"pkg:alpm/arch/python-pip@21.0-1?arch=any">>,
                    <<"pkg:alpm/arch/containers-common@1:0.47.4-4?arch=x86_64">>
                ],
            name_definition =>
                #{
                    case_sensitive => false,
                    native_name => <<"name">>,
                    note =>
                        <<"The name is the package name. It is not case sensitive and must be lowercased.">>,
                    requirement => <<"required">>
                },
            namespace_definition =>
                #{
                    case_sensitive => false,
                    native_name => <<"vendor">>,
                    normalization_rules =>
                        [<<"It is not case sensitive and must be lowercased.">>],
                    note =>
                        <<"The namespace is the vendor such as arch, arch32, archarm, manjaro or msys.">>,
                    requirement => <<"required">>
                },
            qualifiers_definition =>
                [
                    #{
                        description =>
                            <<"The arch is the qualifiers key for a package architecture.">>,
                        key => <<"arch">>,
                        native_name => <<"arch">>,
                        requirement => <<"optional">>
                    }
                ],
            repository =>
                #{
                    note =>
                        <<"There is no default package repository; this should be implied either from the distro qualifiers key  or using a repository base url as  repository_url qualifiers key.">>,
                    use_repository => true
                },
            type => <<"alpm">>,
            type_name => <<"Arch Linux package">>,
            version_definition =>
                #{
                    case_sensitive => true,
                    native_name => <<"version">>,
                    normalization_rules =>
                        [
                            <<"normalize version as specified in vercmp(8) at https://man.archlinux.org/man/vercmp.8#DESCRIPTION as part of alpm.">>
                        ],
                    note =>
                        <<"The version is the version of the package as specified in vercmp(8) at (https://man.archlinux.org/man/vercmp.8#DESCRIPTION as part of alpm.">>,
                    requirement => <<"optional">>
                }
        },
        #{
            '$id' => <<"https://packageurl.org/types/apk-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description => <<"Alpine Linux APK-based packages">>,
            examples =>
                [
                    <<"pkg:apk/alpine/curl@7.83.0-r0?arch=x86">>,
                    <<"pkg:apk/alpine/apk@2.12.9-r3?arch=x86">>
                ],
            name_definition =>
                #{
                    case_sensitive => false,
                    native_name => <<"name">>,
                    note =>
                        <<"The name is the package name. It is not case sensitive and must be lowercased.">>,
                    requirement => <<"required">>
                },
            namespace_definition =>
                #{
                    case_sensitive => false,
                    native_name => <<"vendor">>,
                    note =>
                        <<"The namespace is the vendor such as alpine or openwrt. It is not case sensitive and must be lowercased.">>,
                    requirement => <<"required">>
                },
            note =>
                <<"not to be confused with Android packages with a .apk extension.">>,
            qualifiers_definition =>
                [
                    #{
                        description =>
                            <<"The arch is the qualifiers key for a package architecture.">>,
                        key => <<"arch">>
                    }
                ],
            repository =>
                #{
                    note =>
                        <<"There is no default package repository; this should be implied either from the distro qualifiers key  or using a repository base url as repository_url qualifiers key.">>,
                    use_repository => true
                },
            type => <<"apk">>,
            type_name => <<"APK-based packages">>,
            version_definition =>
                #{
                    native_name => <<"version">>,
                    note => <<"The version is a package version as expected by apk.">>,
                    requirement => <<"optional">>
                }
        },
        #{
            '$id' => <<"https://packageurl.org/types/bazel-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description =>
                <<"Bazel modules as specified at https://bazel.build/external/module">>,
            examples =>
                [
                    <<"pkg:bazel/rules_java@7.8.0">>,
                    <<"pkg:bazel/curl@8.8.0.bcr.1">>,
                    <<"pkg:bazel/curl@8.8.0?repository_url=https://example.org/bazel-registry">>,
                    <<"pkg:bazel/rules_java@8.5.0#java/runfiles">>,
                    <<"pkg:bazel/rules_java@8.5.0#java/runfiles:runfiles">>,
                    <<"pkg:bazel/rules_go@0.48.0#go">>
                ],
            name_definition =>
                #{
                    note => <<"The name as defined in the MODULE.bazel file">>,
                    requirement => <<"required">>
                },
            namespace_definition =>
                #{
                    note => <<"Bazel modules do not use namespaces">>,
                    requirement => <<"prohibited">>
                },
            qualifiers_definition =>
                [
                    #{
                        default_value => <<"https://bcr.bazel.build">>,
                        description =>
                            <<"The URL of the registry that hosts this Bazel module. If not specified, it defaults to the BCR URL.">>,
                        key => <<"repository_url">>,
                        native_name => <<"registry">>,
                        requirement => <<"optional">>
                    }
                ],
            reference_urls => [<<"https://bazel.build/external/module">>],
            repository =>
                #{
                    default_repository_url => <<"https://bcr.bazel.build">>,
                    note =>
                        <<"The default repository is the Bazel Central Registry (BCR)">>,
                    use_repository => true
                },
            subpath_definition =>
                #{
                    native_name => <<"label">>,
                    note =>
                        <<"The optional subpath MAY refer to a label of a particular package or target in the module (https://bazel.build/concepts/labels). The label MUST NOT include a repo name and the leading '//' MUST be omitted. When referring to targets, the label MUST include the name of the target, separated from the package by ':'. If there is no target name, subpath is assumed to refer to the whole package.">>,
                    requirement => <<"optional">>
                },
            type => <<"bazel">>,
            type_name => <<"Bazel modules">>,
            version_definition =>
                #{
                    note =>
                        <<"The version as defined in the MODULE.bazel file. Uses a relaxed semantic versioning format described at https://bazel.build/external/module#version-format.">>,
                    requirement => <<"optional">>
                }
        },
        #{
            '$id' => <<"https://packageurl.org/types/bitbucket-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description => <<"Bitbucket-based packages">>,
            examples =>
                [<<"pkg:bitbucket/birkenfeld/pygments-main@244fd47e07d1014f0aed9c">>],
            name_definition =>
                #{
                    case_sensitive => false,
                    native_name => <<"repository name">>,
                    note =>
                        <<"The name is the repository name. It is not case sensitive and must be lowercased.">>,
                    requirement => <<"required">>
                },
            namespace_definition =>
                #{
                    case_sensitive => false,
                    native_name => <<"user or organization">>,
                    note =>
                        <<"The namespace is the user or organization. It is not case sensitive and must be lowercased.">>,
                    requirement => <<"required">>
                },
            repository =>
                #{
                    default_repository_url => <<"https://bitbucket.org">>,
                    use_repository => true
                },
            type => <<"bitbucket">>,
            type_name => <<"Bitbucket">>,
            version_definition =>
                #{
                    native_name => <<"commit or tag">>,
                    note => <<"The version is a commit or tag.">>,
                    requirement => <<"optional">>
                }
        },
        #{
            '$id' => <<"https://packageurl.org/types/bitnami-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description => <<"Bitnami-based packages">>,
            examples =>
                [
                    <<"pkg:bitnami/wordpress?distro=debian-12">>,
                    <<"pkg:bitnami/wordpress@6.2.0?distro=debian-12">>,
                    <<"pkg:bitnami/wordpress@6.2.0?arch=arm64&distro=debian-12">>,
                    <<"pkg:bitnami/wordpress@6.2.0?arch=arm64&distro=photon-4">>
                ],
            name_definition =>
                #{
                    case_sensitive => false,
                    native_name => <<"name">>,
                    note => <<"The name is the component name. It must be lowercased.">>,
                    requirement => <<"required">>
                },
            namespace_definition =>
                #{note => <<"there is no namespace">>, requirement => <<"prohibited">>},
            qualifiers_definition =>
                [
                    #{
                        default_value => <<"amd64">>,
                        description =>
                            <<"The arch is the qualifiers key for a package architecture. Available values are amd64 (default) and arm64.">>,
                        key => <<"arch">>
                    },
                    #{
                        description =>
                            <<"The distro is the qualifiers key for the distribution associated to the package.">>,
                        key => <<"distro">>
                    }
                ],
            repository =>
                #{
                    default_repository_url =>
                        <<"https://downloads.bitnami.com/files/stacksmith">>,
                    use_repository => true
                },
            type => <<"bitnami">>,
            type_name => <<"Bitnami">>,
            version_definition =>
                #{
                    native_name =>
                        <<"full package version, including version and revision">>,
                    note =>
                        <<"The version is the full Bitnami package version, including version and revision.">>,
                    requirement => <<"optional">>
                }
        },
        #{
            '$id' => <<"https://packageurl.org/types/cargo-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description => <<"Cargo packages for Rust">>,
            examples =>
                [
                    <<"pkg:cargo/rand@0.7.2">>,
                    <<"pkg:cargo/clap@2.33.0">>,
                    <<"pkg:cargo/structopt@0.3.11">>
                ],
            name_definition =>
                #{
                    case_sensitive => true,
                    native_name => <<"name">>,
                    note => <<"The name is the repository name.">>,
                    requirement => <<"required">>
                },
            namespace_definition =>
                #{note => <<"there is no namespace">>, requirement => <<"prohibited">>},
            repository =>
                #{
                    default_repository_url => <<"https://crates.io/">>,
                    use_repository => true
                },
            type => <<"cargo">>,
            type_name => <<"Cargo">>,
            version_definition =>
                #{
                    native_name => <<"version">>,
                    note => <<"The version is the package version.">>,
                    requirement => <<"optional">>
                }
        },
        #{
            '$id' => <<"https://packageurl.org/types/chrome-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description =>
                <<"Chrome Browser Extensions. Note: there are currently no officially documented APIs, further there appears to be no way to query different versions of a package - there only seems to be responses on the latest version. To this end the version component of a chrome purl can be optional. Two known data sources are a sitemap which can be crawled to discover (some) extensions at https://chromewebstore.google.com/sitemap, and an 'updatecheck' API which you can read about here https://github.com/Rob--W/crxviewer , and perhaps here https://github.com/chromium/chromium/blob/main/docs/updater/protocol_3_1.md">>,
            examples =>
                [
                    <<"pkg:chrome-extension/hlepfoohegkhhmjieoechaddaejaokhf@25.7.1">>,
                    <<"pkg:chrome-extension/dncgedbnidfkppmdgfgidcepclnokpkb@6.0.2.3611">>,
                    <<"pkg:chrome-extension/kanfjhdeebkfgkbmnfknhejpadhlmiab@0.6">>,
                    <<"pkg:chrome-extension/dlpngalgnefjeiefhmpklpfiohadpglk@1">>,
                    <<"pkg:chrome-extension/dlpngalgnefjeiefhmpklpfiohadpglk">>
                ],
            name_definition =>
                #{
                    case_sensitive => false,
                    native_name => <<"extension_id">>,
                    note =>
                        <<"The name is a 32 characters a-z and is case insensitive. This is not the same as the display name which is human readable and may vary with locale.">>,
                    permitted_characters => <<"^[a-z]{32}$">>,
                    requirement => <<"required">>
                },
            namespace_definition =>
                #{note => <<"There is no namespace">>, requirement => <<"prohibited">>},
            repository =>
                #{
                    default_repository_url =>
                        <<"https://https://chromewebstore.google.com/">>,
                    note =>
                        <<"There is no documented API, only a sitemap and 'updatecheck' endpoints.">>,
                    use_repository => true
                },
            type => <<"chrome-extension">>,
            type_name => <<"Chrome Browser Extensions">>,
            version_definition =>
                #{
                    native_name => <<"version">>,
                    note =>
                        <<"The chrome extension version is semver-like but 1-4 segments. See https://developer.chrome.com/docs/extensions/reference/manifest/version">>,
                    permitted_characters => <<"^\\d+(\\.\\d+){0,3}$">>,
                    requirement => <<"optional">>
                }
        },
        #{
            '$id' => <<"https://packageurl.org/types/cocoapods-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description => <<"CocoaPods pods">>,
            examples =>
                [
                    <<"pkg:cocoapods/AFNetworking@4.0.1">>,
                    <<"pkg:cocoapods/MapsIndoors@3.24.0">>,
                    <<"pkg:cocoapods/ShareKit@2.0#Twitter">>,
                    <<"pkg:cocoapods/GoogleUtilities@7.5.2#NSData+zlib">>
                ],
            name_definition =>
                #{
                    case_sensitive => true,
                    native_name => <<"pod name">>,
                    note =>
                        <<"The name is the pod name and is case sensitive, cannot contain whitespace, a plus (+) character, or begin with a period (.).">>,
                    requirement => <<"required">>
                },
            namespace_definition =>
                #{note => <<"there is no namespace">>, requirement => <<"prohibited">>},
            repository =>
                #{
                    default_repository_url => <<"https://cdn.cocoapods.org/">>,
                    use_repository => true
                },
            subpath_definition =>
                #{
                    note =>
                        <<"The purl subpath is used to represent a pods subspec (if present).">>,
                    requirement => <<"optional">>
                },
            type => <<"cocoapods">>,
            type_name => <<"CocoaPods">>,
            version_definition =>
                #{
                    native_name => <<"package version">>,
                    note => <<"The version is the package version.">>,
                    requirement => <<"optional">>
                }
        },
        #{
            '$id' => <<"https://packageurl.org/types/composer-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description => <<"Composer PHP packages">>,
            examples => [<<"pkg:composer/laravel/laravel@5.5.0">>],
            name_definition =>
                #{
                    case_sensitive => false,
                    native_name => <<"name">>,
                    note =>
                        <<"The name is not case sensitive and must be lowercased. Private, local packages may have no name. In this case you cannot create a purl for these.">>,
                    requirement => <<"required">>
                },
            namespace_definition =>
                #{
                    case_sensitive => false,
                    native_name => <<"vendor">>,
                    note =>
                        <<"The namespace is the vendor. The namespace is not case sensitive and must be lowercased.">>,
                    requirement => <<"required">>
                },
            repository =>
                #{
                    default_repository_url => <<"https://packagist.org">>,
                    use_repository => true
                },
            type => <<"composer">>,
            type_name => <<"Composer">>,
            version_definition =>
                #{native_name => <<"version">>, requirement => <<"optional">>}
        },
        #{
            '$id' => <<"https://packageurl.org/types/conan-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description =>
                <<"Conan C/C++ packages. The purl is designed to closely resemble the Conan-native <package-name>/<package-version>@<user>/<channel> syntax for package references as specified in https://docs.conan.io/en/1.46/cheatsheet.html#package-terminology">>,
            examples =>
                [
                    <<"pkg:conan/openssl@3.0.3">>,
                    <<"pkg:conan/openssl.org/openssl@3.0.3?user=bincrafters&channel=stable">>,
                    <<"pkg:conan/openssl.org/openssl@3.0.3?arch=x86_64&build_type=Debug&compiler=Visual%20Studio&compiler.runtime=MDd&compiler.version=16&os=Windows&shared=True&rrev=93a82349c31917d2d674d22065c7a9ef9f380c8e&prev=b429db8a0e324114c25ec387bfd8281f330d7c5c">>
                ],
            name_definition =>
                #{
                    native_name => <<"package-name">>,
                    note => <<"The Conan <package-name>.">>,
                    requirement => <<"required">>
                },
            namespace_definition =>
                #{
                    native_name => <<"vendor">>,
                    note => <<"The vendor of the package.">>,
                    requirement => <<"optional">>
                },
            note =>
                <<"Additional qualifiers can be used to distinguish Conan packages with different settings or options, e.g. os=Linux, build_type=Debug or shared=True. If no additional qualifiers are used to distinguish Conan packages build with different settings or options, then the purl is ambiguous and it is up to the user to work out which package is being referred to (e.g. with context information).">>,
            qualifiers_definition =>
                [
                    #{
                        description =>
                            <<"The Conan <user>. Only required if the Conan package was published with <user>.">>,
                        key => <<"user">>,
                        native_name => <<"user">>,
                        requirement => <<"optional">>
                    },
                    #{
                        description =>
                            <<"The Conan <channel>. Only required if the Conan package was published with Conan <channel>.">>,
                        key => <<"channel">>,
                        native_name => <<"channel">>,
                        requirement => <<"optional">>
                    },
                    #{
                        description =>
                            <<"The Conan recipe revision (optional). If omitted, the purl refers to the latest recipe revision available for the given version.">>,
                        key => <<"rrev">>,
                        native_name => <<"recipe revision">>,
                        requirement => <<"optional">>
                    },
                    #{
                        description =>
                            <<"The Conan package revision (optional). If omitted, the purl refers to the latest package revision available for the given version and recipe revision.">>,
                        key => <<"prev">>,
                        native_name => <<"package revision">>,
                        requirement => <<"optional">>
                    }
                ],
            repository =>
                #{
                    default_repository_url => <<"https://center.conan.io">>,
                    use_repository => true
                },
            type => <<"conan">>,
            type_name => <<"Conan C/C++ packages">>,
            version_definition =>
                #{
                    native_name => <<"package-version">>,
                    note => <<"The Conan <package-version>.">>,
                    requirement => <<"optional">>
                }
        },
        #{
            '$id' => <<"https://packageurl.org/types/conda-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description => <<"conda is for Conda packages">>,
            examples =>
                [
                    <<"pkg:conda/absl-py@0.4.1?build=py36h06a4308_0&channel=main&subdir=linux-64&type=tar.bz2">>
                ],
            name_definition =>
                #{
                    native_name => <<"name">>,
                    note => <<"The name is the package name.">>,
                    requirement => <<"required">>
                },
            namespace_definition =>
                #{note => <<"there is no namspace">>, requirement => <<"prohibited">>},
            qualifiers_definition =>
                [
                    #{description => <<"the build string.">>, key => <<"build">>},
                    #{
                        description => <<"the package stored location.">>,
                        key => <<"channel">>
                    },
                    #{description => <<"the associated platform.">>, key => <<"subdir">>},
                    #{description => <<"package type.">>, key => <<"type">>}
                ],
            repository =>
                #{
                    default_repository_url => <<"https://repo.anaconda.com">>,
                    use_repository => true
                },
            type => <<"conda">>,
            type_name => <<"Conda">>,
            version_definition =>
                #{
                    native_name => <<"version">>,
                    note => <<"The version is the package version.">>,
                    requirement => <<"optional">>
                }
        },
        #{
            '$id' => <<"https://packageurl.org/types/cpan-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description => <<"Perl package distributions published on CPAN">>,
            examples =>
                [
                    <<"pkg:cpan/GDT/URI-PackageURL">>,
                    <<"pkg:cpan/OALDERS/libwww-perl@6.76">>,
                    <<"pkg:cpan/DROLSKY/DateTime@1.55?repository_url=backpan.perl.org">>
                ],
            name_definition =>
                #{
                    case_sensitive => true,
                    native_name => <<"distribution name">>,
                    note =>
                        <<"The name is the distribution name and is case sensitive. A distribution name MUST NOT contain the string '::'">>,
                    requirement => <<"required">>
                },
            namespace_definition =>
                #{
                    native_name => <<"CPAN ID of the author/publisher">>,
                    note => <<"It MUST be written uppercase and is required">>,
                    requirement => <<"required">>
                },
            note =>
                <<"The previous CPAN PURL type specification allowed module names (e.g. URI::PackageURL) to be used as PURL 'name' while also omitting the PURL 'namespace'. The parser MUST emit an error when a module is specified as a PURL 'name' or detect '::' characters.">>,
            qualifiers_definition =>
                [
                    #{
                        description =>
                            <<"CPAN/MetaCPAN/BackPAN/DarkPAN repository base URL">>,
                        key => <<"repository_url">>,
                        requirement => <<"optional">>
                    },
                    #{
                        description => <<"URL of package or distribution">>,
                        key => <<"download_url">>,
                        requirement => <<"optional">>
                    },
                    #{
                        description => <<"extra URL for a package version control system">>,
                        key => <<"vcs_url">>,
                        requirement => <<"optional">>
                    },
                    #{
                        default_value => <<"tar.gz">>,
                        description => <<"file extension">>,
                        key => <<"ext">>,
                        requirement => <<"optional">>
                    }
                ],
            repository =>
                #{
                    default_repository_url => <<"https://www.cpan.org/">>,
                    use_repository => true
                },
            type => <<"cpan">>,
            type_name => <<"CPAN">>,
            version_definition =>
                #{
                    native_name => <<"version">>,
                    note => <<"The version is the distribution version">>,
                    requirement => <<"optional">>
                }
        },
        #{
            '$id' => <<"https://packageurl.org/types/cran-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description => <<"CRAN R packages">>,
            examples =>
                [
                    <<"pkg:cran/A3@1.0.0">>,
                    <<"pkg:cran/rJava@1.0-4">>,
                    <<"pkg:cran/caret@6.0-88">>
                ],
            name_definition =>
                #{
                    case_sensitive => true,
                    native_name => <<"name">>,
                    note =>
                        <<"The name is the package name and is case sensitive, but there cannot be two packages on CRAN with the same name ignoring case.">>,
                    requirement => <<"required">>
                },
            namespace_definition =>
                #{note => <<"there is no namespace">>, requirement => <<"prohibited">>},
            repository =>
                #{
                    default_repository_url => <<"https://cran.r-project.org">>,
                    use_repository => true
                },
            type => <<"cran">>,
            type_name => <<"CRAN">>,
            version_definition =>
                #{
                    native_name => <<"version">>,
                    note => <<"The version is the package version.">>,
                    requirement => <<"optional">>
                }
        },
        #{
            '$id' => <<"https://packageurl.org/types/deb-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description =>
                <<"Debian packages, Debian derivatives, and Ubuntu packages">>,
            examples =>
                [
                    <<"pkg:deb/debian/curl@7.50.3-1?arch=i386&distro=jessie">>,
                    <<"pkg:deb/debian/dpkg@1.19.0.4?arch=amd64&distro=stretch">>,
                    <<"pkg:deb/ubuntu/dpkg@1.19.0.4?arch=amd64">>,
                    <<"pkg:deb/debian/attr@1:2.4.47-2?arch=source">>,
                    <<"pkg:deb/debian/attr@1:2.4.47-2%2Bb1?arch=amd64">>
                ],
            name_definition =>
                #{
                    case_sensitive => false,
                    native_name => <<"name">>,
                    note => <<"The name is not case sensitive and must be lowercased.">>,
                    requirement => <<"required">>
                },
            namespace_definition =>
                #{
                    case_sensitive => false,
                    native_name => <<"vendor">>,
                    note =>
                        <<"The namespace is the \"vendor\" name such as \"debian\" or \"ubuntu\". It is not case sensitive and must be lowercased.">>,
                    requirement => <<"required">>
                },
            qualifiers_definition =>
                [
                    #{
                        description =>
                            <<"arch is the qualifiers key for a package architecture. The special value arch=source identifies a Debian source package that usually consists of a Debian Source control file (.dsc) and corresponding upstream and Debian sources. The dpkg-query command can print the name and version of the corresponding source package of a binary package, e.g. dpkg-query -f ${source:Package} ${source:Version} -W <binary package name>">>,
                        key => <<"arch">>
                    }
                ],
            repository =>
                #{
                    note =>
                        <<"There is no default package repository, this should be implied either from the distro qualifiers key or using a base url as a repository_url qualifiers key.">>,
                    use_repository => true
                },
            type => <<"deb">>,
            type_name => <<"Debian package">>,
            version_definition =>
                #{
                    native_name => <<"version">>,
                    note =>
                        <<"The version is the version of the binary (or source) package.">>,
                    requirement => <<"optional">>
                }
        },
        #{
            '$id' => <<"https://packageurl.org/types/docker-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description => <<"for Docker images">>,
            examples =>
                [
                    <<"pkg:docker/cassandra@latest">>,
                    <<"pkg:docker/smartentry/debian@dc437cc87d10">>,
                    <<"pkg:docker/customer/dockerimage@sha256%3A244fd47e07d10?repository_url=gcr.io">>
                ],
            name_definition =>
                #{native_name => <<"name">>, requirement => <<"required">>},
            namespace_definition =>
                #{
                    note =>
                        <<"The namespace is the registry/user/organization if present.">>,
                    requirement => <<"optional">>
                },
            repository =>
                #{
                    default_repository_url => <<"https://hub.docker.com">>,
                    use_repository => true
                },
            type => <<"docker">>,
            type_name => <<"Docker image">>,
            version_definition =>
                #{
                    note =>
                        <<"The version should be the image id sha256 or a tag. Since tags can be moved, a sha256 image id is preferred.">>,
                    requirement => <<"optional">>
                }
        },
        #{
            '$id' => <<"https://packageurl.org/types/gem-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description => <<"RubyGems">>,
            examples =>
                [
                    <<"pkg:gem/ruby-advisory-db-check@0.12.4">>,
                    <<"pkg:gem/jruby-launcher@1.1.2?platform=java">>
                ],
            name_definition =>
                #{native_name => <<"name">>, requirement => <<"required">>},
            namespace_definition =>
                #{note => <<"There is no namespace">>, requirement => <<"prohibited">>},
            qualifiers_definition =>
                [
                    #{
                        default_value => <<"ruby">>,
                        description =>
                            <<"qualifiers key is used to specify an alternative platform. such as java for JRuby. The implied default is ruby for Ruby MRI.">>,
                        key => <<"platform">>,
                        native_name => <<"platform">>,
                        requirement => <<"optional">>
                    }
                ],
            repository =>
                #{
                    default_repository_url => <<"https://rubygems.org">>,
                    use_repository => true
                },
            type => <<"gem">>,
            type_name => <<"RubyGems">>,
            version_definition =>
                #{native_name => <<"version">>, requirement => <<"optional">>}
        },
        #{
            '$id' => <<"https://packageurl.org/types/generic-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description =>
                <<"The generic type is for plain, generic packages that do not fit anywhere else such as for \"upstream-from-distro\" packages. In particular this is handy for a plain version control repository such as a bare git repo in combination with a vcs_url.">>,
            examples =>
                [
                    <<"pkg:generic/openssl@1.1.10g">>,
                    <<"pkg:generic/openssl@1.1.10g?download_url=https://openssl.org/source/openssl-1.1.0g.tar.gz&checksum=sha256:de4d501267da">>,
                    <<"pkg:generic/bitwarderl?vcs_url=git%2Bhttps://git.fsfe.org/dxtr/bitwarderl%40cc55108da32">>
                ],
            name_definition =>
                #{
                    note =>
                        <<"as for other type, the name component is mandatory. In the worst case it can be a file or directory name.">>,
                    requirement => <<"required">>
                },
            namespace_definition =>
                #{
                    note => <<"there is no generic namespace definition">>,
                    requirement => <<"optional">>
                },
            note =>
                <<"When possible another or a new purl type should be used instead of using the generic type and eventually contributed back to this specification. Example have been truncated for brevity">>,
            qualifiers_definition =>
                [
                    #{
                        description =>
                            <<"A download_url and checksum may be provided in qualifiers or as separate attributes outside of a purl for proper identification and location.">>,
                        key => <<"download_url">>
                    },
                    #{
                        description =>
                            <<"A checksum may be provided in qualifiers or as separate attributes outside of a purl for proper identification and location.">>,
                        key => <<"checksum">>
                    }
                ],
            repository =>
                #{note => <<"There is no default repository.">>, use_repository => false},
            type => <<"generic">>,
            type_name => <<"Generic Package">>
        },
        #{
            '$id' => <<"https://packageurl.org/types/github-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description => <<"GitHub-based packages">>,
            examples =>
                [
                    <<"pkg:github/package-url/purl-spec@244fd47e07d1004">>,
                    <<"pkg:github/package-url/purl-spec@244fd47e07d1004#everybody/loves/dogs">>
                ],
            name_definition =>
                #{
                    case_sensitive => false,
                    native_name => <<"repository name">>,
                    note =>
                        <<"The name is the repository name. It is not case sensitive and must be lowercased.">>,
                    requirement => <<"required">>
                },
            namespace_definition =>
                #{
                    case_sensitive => false,
                    native_name => <<"user or organization">>,
                    note =>
                        <<"The namespace is the user or organization. It is not case sensitive and must be lowercased.">>,
                    requirement => <<"required">>
                },
            repository =>
                #{
                    default_repository_url => <<"https://github.com">>,
                    use_repository => true
                },
            type => <<"github">>,
            type_name => <<"GitHub">>,
            version_definition =>
                #{
                    native_name => <<"commit or tag">>,
                    note => <<"The version is a commit or tag.">>,
                    requirement => <<"optional">>
                }
        },
        #{
            '$id' => <<"https://packageurl.org/types/golang-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description => <<"Go packages">>,
            examples =>
                [
                    <<"pkg:golang/github.com/gorilla/context@234fd47e07d1004f0aed9c">>,
                    <<"pkg:golang/google.golang.org/genproto#googleapis/api/annotations">>,
                    <<"pkg:golang/github.com/gorilla/context@234fd47e07d1004f0aed9c#api">>
                ],
            name_definition =>
                #{
                    case_sensitive => true,
                    note => <<"The name must be lowercased.">>,
                    requirement => <<"required">>
                },
            namespace_definition =>
                #{
                    case_sensitive => true,
                    note => <<"The namespace must be lowercased.">>,
                    requirement => <<"required">>
                },
            note =>
                <<"The current definition predates Go modules and has several practical problems, and in particular it is impossible to determine what is a module and what is a package short of having full access to the source code or making an API call to the Go module proxy.">>,
            repository =>
                #{
                    note =>
                        <<"There is no default package repository, this is implied in the namespace using the go get command conventions. In practice the Go module proxy acts as a public default repository.">>,
                    use_repository => true
                },
            subpath_definition =>
                #{
                    note =>
                        <<"The subpath is used to point to a subpath inside a package.">>,
                    requirement => <<"optional">>
                },
            type => <<"golang">>,
            type_name => <<"Go package">>,
            version_definition =>
                #{
                    note =>
                        <<"The version is often empty when a commit is not specified and should be the commit in most cases when available.">>,
                    requirement => <<"optional">>
                }
        },
        #{
            '$id' => <<"https://packageurl.org/types/hackage-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description => <<"Haskell packages">>,
            examples =>
                [
                    <<"pkg:hackage/a50@0.5">>,
                    <<"pkg:hackage/AC-HalfInteger@1.2.1">>,
                    <<"pkg:hackage/3d-graphics-examples@0.0.0.2">>
                ],
            name_definition =>
                #{
                    case_sensitive => true,
                    native_name => <<"name">>,
                    normalization_rules => [<<"Apply kebab-case">>],
                    note => <<"The name is case sensitive and use kebab-case.">>,
                    requirement => <<"required">>
                },
            namespace_definition =>
                #{note => <<"there is no namespace">>, requirement => <<"prohibited">>},
            repository =>
                #{
                    default_repository_url => <<"https://hackage.haskell.org">>,
                    use_repository => true
                },
            type => <<"hackage">>,
            type_name => <<"Haskell package">>,
            version_definition =>
                #{
                    native_name => <<"version">>,
                    note => <<"The version is package version.">>,
                    requirement => <<"optional">>
                }
        },
        #{
            '$id' => <<"https://packageurl.org/types/hex-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description => <<"Hex packages">>,
            examples =>
                [
                    <<"pkg:hex/jason@1.1.2">>,
                    <<"pkg:hex/acme/foo@2.3.">>,
                    <<"pkg:hex/phoenix_html@2.13.3#priv/static/phoenix_html.js">>,
                    <<"pkg:hex/bar@1.2.3?repository_url=https://myrepo.example.com">>
                ],
            name_definition =>
                #{
                    case_sensitive => false,
                    native_name => <<"name">>,
                    note => <<"The name is not case sensitive and must be lowercased.">>,
                    requirement => <<"required">>
                },
            namespace_definition =>
                #{
                    case_sensitive => false,
                    native_name => <<"organization for private packages">>,
                    note =>
                        <<"The namespace is optional; it may be used to specify the organization for private packages on hex.pm. It is not case sensitive and must be lowercased.">>,
                    requirement => <<"optional">>
                },
            repository =>
                #{
                    default_repository_url => <<"https://repo.hex.pm">>,
                    use_repository => true
                },
            type => <<"hex">>,
            type_name => <<"Hex">>,
            version_definition =>
                #{native_name => <<"version">>, requirement => <<"optional">>}
        },
        #{
            '$id' => <<"https://packageurl.org/types/huggingfaces-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description => <<"Hugging Face ML models">>,
            examples =>
                [
                    <<"pkg:huggingface/distilbert-base-uncased@043235d6088ecd3dd5fb5ca3592b6913fd516027">>,
                    <<"pkg:huggingface/microsoft/deberta-v3-base@559062ad13d311b87b2c455e67dcd5f1c8f65111?repository_url=https://hub-ci.huggingface.co">>
                ],
            name_definition =>
                #{
                    case_sensitive => true,
                    native_name => <<"model repository name">>,
                    note =>
                        <<"The name is the model repository name. It is case sensitive.">>,
                    requirement => <<"required">>
                },
            namespace_definition =>
                #{
                    case_sensitive => true,
                    native_name => <<"model repository username or organization">>,
                    note =>
                        <<"The namespace is the model repository username or organization, if present. It is case sensitive.">>,
                    requirement => <<"required">>
                },
            repository =>
                #{
                    note => <<"The default repository is https://huggingface.co.">>,
                    use_repository => true
                },
            type => <<"huggingface">>,
            type_name => <<"HuggingFace models">>,
            version_definition =>
                #{
                    case_sensitive => false,
                    native_name => <<"model revision Git commit hash">>,
                    note =>
                        <<"The version is the model revision Git commit hash. It is case insensitive and must be lowercased in the package URL.">>,
                    requirement => <<"optional">>
                }
        },
        #{
            '$id' => <<"https://packageurl.org/types/julia-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description => <<"Julia packages">>,
            examples =>
                [
                    <<"pkg:julia/Dates@1.9.0?uuid=ade2ca70-3891-5945-98fb-dc099432e06a">>,
                    <<"pkg:julia/Dates?uuid=ade2ca70-3891-5945-98fb-dc099432e06a">>,
                    <<"pkg:julia/RegisterQD@0.3.1?uuid=ac24ea0c-1830-11e9-18d4-81f172323054">>,
                    <<"pkg:julia/RegisterQD@0.3.1?uuid=ac24ea0c-1830-11e9-18d4-81f172323054&repository_url=https://github.com/HolyLab/HolyLabRegistry">>
                ],
            name_definition =>
                #{
                    case_sensitive => true,
                    native_name => <<"name">>,
                    note =>
                        <<"The name is the package name (without a `.jl` suffix). The name is case sensitive.">>,
                    requirement => <<"required">>
                },
            namespace_definition =>
                #{note => <<"there is no namespace">>, requirement => <<"prohibited">>},
            qualifiers_definition =>
                [
                    #{
                        description => <<"The Julia package UUID.">>,
                        key => <<"uuid">>,
                        native_name => <<"uuid">>,
                        requirement => <<"required">>
                    }
                ],
            repository =>
                #{
                    default_repository_url =>
                        <<"https://github.com/JuliaRegistries/General">>,
                    use_repository => true
                },
            type => <<"julia">>,
            type_name => <<"Julia Package">>,
            version_definition =>
                #{
                    native_name => <<"version">>,
                    note => <<"The version is the package version.">>,
                    requirement => <<"optional">>
                }
        },
        #{
            '$id' => <<"https://packageurl.org/types/luarocks-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description => <<"Lua packages installed with LuaRocks">>,
            examples =>
                [
                    <<"pkg:luarocks/luasocket@3.1.0-1">>,
                    <<"pkg:luarocks/hisham/luafilesystem@1.8.0-1">>,
                    <<"pkg:luarocks/username/packagename@0.1.0-1?repository_url=https://example.com/private_rocks_server/">>
                ],
            name_definition =>
                #{
                    case_sensitive => false,
                    native_name => <<"name">>,
                    note =>
                        <<"The LuaRocks package name. It is case insensitive, but lowercase is encouraged since package names are normalized to ASCII lowercase.">>,
                    requirement => <<"required">>
                },
            namespace_definition =>
                #{
                    case_sensitive => false,
                    native_name => <<"user manifest">>,
                    note =>
                        <<"The user manifest under which the package is registered. If not given, the root manifest is assumed. It is case insensitive, but lowercase is encouraged since namespaces are normalized to ASCII lowercase.">>,
                    requirement => <<"optional">>
                },
            qualifiers_definition =>
                [
                    #{
                        description =>
                            <<"The LuaRocks rocks server to be used; useful in case a private server is used (optional). If omitted, https://luarocks.org as default server is assumed.">>,
                        key => <<"repository_url">>
                    }
                ],
            repository => #{use_repository => true},
            type => <<"luarocks">>,
            type_name => <<"LuaRocks">>,
            version_definition =>
                #{
                    case_sensitive => true,
                    native_name =>
                        <<"full package version, including module version and rockspec revision">>,
                    note =>
                        <<"The full LuaRocks package version, including module version and rockspec revision. It is case sensitive, and lowercase must be used to avoid compatibility issues with older LuaRocks versions. The full version number is required to uniquely identify a version.">>,
                    requirement => <<"optional">>
                }
        },
        #{
            '$id' => <<"https://packageurl.org/types/maven-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description => <<"PURL type for Maven JARs and related artifacts.">>,
            examples =>
                [
                    <<"pkg:maven/org.apache.xmlgraphics/batik-anim@1.9.1">>,
                    <<"pkg:maven/org.apache.xmlgraphics/batik-anim@1.9.1?type=pom">>,
                    <<"pkg:maven/org.apache.xmlgraphics/batik-anim@1.9.1?classifier=sources">>,
                    <<"pkg:maven/org.apache.xmlgraphics/batik-anim@1.9.1?type=zip&classifier=dist">>,
                    <<"pkg:maven/net.sf.jacob-projec/jacob@1.14.3?classifier=x86&type=dll">>,
                    <<"pkg:maven/net.sf.jacob-projec/jacob@1.14.3?classifier=x64&type=dll">>,
                    <<"pkg:maven/groovy/groovy@1.0?repository_url=https://maven.google.com">>
                ],
            name_definition =>
                #{
                    case_sensitive => true,
                    native_name => <<"artifactId">>,
                    note => <<"The artifact id is the name.">>,
                    requirement => <<"required">>
                },
            namespace_definition =>
                #{
                    case_sensitive => true,
                    native_name => <<"groupId">>,
                    note => <<"The group id is the namespace.">>,
                    requirement => <<"required">>
                },
            qualifiers_definition =>
                [
                    #{
                        description =>
                            <<"The maven classifier as defined in the POM documentation.">>,
                        key => <<"classifier">>,
                        native_name => <<"classifier">>,
                        requirement => <<"optional">>
                    },
                    #{
                        default_value => <<"jar">>,
                        description =>
                            <<"The maven type as defined in the POM documentation. Note that Maven uses a concept / coordinate called packaging which does not map directly 1:1 to a file extension. In this use case, we need to construct a link to one of many possible artifacts. Maven itself uses type in a dependency declaration when needed to disambiguate between them.">>,
                        key => <<"type">>,
                        native_name => <<"type">>,
                        requirement => <<"optional">>
                    }
                ],
            repository =>
                #{
                    default_repository_url => <<"https://repo.maven.apache.org/maven2/">>,
                    note =>
                        <<"The Maven Central repository is the public repository for Apache Maven packages. This repository is also mirrored at https://repo1.maven.org/maven2/. Use the standard repository_url qualifier to point to another repository">>,
                    use_repository => true
                },
            type => <<"maven">>,
            type_name => <<"Maven">>,
            version_definition =>
                #{
                    case_sensitive => true,
                    native_name => <<"version">>,
                    requirement => <<"optional">>
                }
        },
        #{
            '$id' => <<"https://packageurl.org/types/mlflow-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description => <<"MLflow ML models (Azure ML, Databricks, etc.)">>,
            examples =>
                [
                    <<"pkg:mlflow/creditfraud@3?repository_url=https://westus2.api.azureml.ms/mlflow/v1.0/subscriptions/a50f2011-fab8-4164-af23-c62881ef8c95/resourceGroups/TestResourceGroup/providers/Microsoft.MachineLearningServices/workspaces/TestWorkspace">>,
                    <<"pkg:mlflow/trafficsigns@10?model_uuid=36233173b22f4c89b451f1228d700d49&run_id=410a3121-2709-4f88-98dd-dba0ef056b0a&repository_url=https://adb-5245952564735461.0.azuredatabricks.net/api/2.0/mlflow">>
                ],
            name_definition =>
                #{
                    note =>
                        <<"The name is the model name. Case sensitivity depends on the server implementation, such as for Azure ML, it is case sensitive and must be kept as-is in the package URL; and for Databricks, it is case insensitive and must be lowercased in the package URL.">>,
                    requirement => <<"required">>
                },
            namespace_definition =>
                #{note => <<"there is no namespace">>, requirement => <<"prohibited">>},
            qualifiers_definition =>
                [
                    #{
                        description =>
                            <<"model_uuid as defined in the MLflow documentation.">>,
                        key => <<"model_uuid">>,
                        native_name => <<"model_uuid">>
                    },
                    #{
                        description => <<"run_id as defined in the MLflow documentation.">>,
                        key => <<"run_id">>,
                        native_name => <<"run_id">>
                    }
                ],
            repository =>
                #{
                    note =>
                        <<"The repository is the MLflow tracking URI. There is no default. Some examples include Azure ML https://<region>.api.azureml.ms/mlflow/v1.0/subscriptions/<subscription-id>/resourceGroups/<resource-group-name>/providers/Microsoft.MachineLearningServices/workspaces/<workspace-name> and Azure Databricks https://adb-<numbers>.<number>.azuredatabricks.net/api/2.0/mlflow and AWS Databricks https://dbc-<alphanumeric>-<alphanumeric>.cloud.databricks.com/api/2.0/mlflow and GCP Databricks https://<numbers>.<number>.gcp.databricks.com/api/2.0/mlflow">>,
                    use_repository => true
                },
            type => <<"mlflow">>,
            type_name => <<"MLflow">>,
            version_definition =>
                #{
                    native_name => <<"version">>,
                    note => <<"The version is the model version.">>,
                    requirement => <<"optional">>
                }
        },
        #{
            '$id' => <<"https://packageurl.org/types/npm-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description => <<"PURL type for npm packages.">>,
            examples =>
                [
                    <<"pkg:npm/foobar@12.3.1">>,
                    <<"pkg:npm/%40angular/animation@12.3.1">>,
                    <<"pkg:npm/mypackage@12.4.5?vcs_url=git://host.com/path/to/repo.git%404345abcd34343">>
                ],
            name_definition =>
                #{
                    case_sensitive => true,
                    native_name => <<"name">>,
                    note =>
                        <<"The package.json spec changed in 2015 to require that a new package 'must not have uppercase letters in the name', but old packages with mixed case names were \"grandfathered in\".">>,
                    requirement => <<"required">>
                },
            namespace_definition =>
                #{
                    case_sensitive => true,
                    native_name => <<"scope">>,
                    note =>
                        <<"The namespace is used for the scope of a scoped NPM package. The npm scope @ sign prefix is always percent encoded, as it was in the early days of npm scope.">>,
                    requirement => <<"optional">>
                },
            repository =>
                #{
                    default_repository_url => <<"https://registry.npmjs.org/">>,
                    note =>
                        <<"The default repository is the npm Registry at https://registry.npmjs.org">>,
                    use_repository => true
                },
            type => <<"npm">>,
            type_name => <<"Node NPM packages">>,
            version_definition =>
                #{
                    case_sensitive => true,
                    native_name => <<"version">>,
                    requirement => <<"optional">>
                }
        },
        #{
            '$id' => <<"https://packageurl.org/types/nuget-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description => <<"NuGet .NET packages">>,
            examples => [<<"pkg:nuget/EnterpriseLibrary.Common@6.0.1304">>],
            name_definition =>
                #{
                    case_sensitive => true,
                    native_name => <<"version">>,
                    note =>
                        <<"Technically the name is case-perserving, but case-insensitive, and NuGet packages archives are case-perserving, while some NuGet API calls demand to lowercase the package name.">>,
                    requirement => <<"required">>
                },
            namespace_definition =>
                #{note => <<"there is no namespace">>, requirement => <<"prohibited">>},
            note =>
                <<"There is no namespace per se even if the common convention is to use dot-separated package names where the first segment is namespace-like.">>,
            repository =>
                #{
                    default_repository_url => <<"https://www.nuget.org">>,
                    use_repository => true
                },
            type => <<"nuget">>,
            type_name => <<"NuGet">>,
            version_definition =>
                #{
                    native_name => <<"version">>,
                    note =>
                        <<"The NuGet version is semver-like but may contain more than three segments">>,
                    requirement => <<"optional">>
                }
        },
        #{
            '$id' => <<"https://packageurl.org/types/oci-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description =>
                <<"For artifacts stored in registries that conform to the OCI Distribution Specification https://github.com/opencontainers/distribution-spec including container images built by Docker and others">>,
            examples =>
                [
                    <<"pkg:oci/debian@sha256%3A244fd47e07d10?repository_url=docker.io/library/debian&arch=amd64&tag=latest">>,
                    <<"pkg:oci/debian@sha256%3A244fd47e07d10?repository_url=ghcr.io/debian&tag=bullseye">>,
                    <<"pkg:oci/static@sha256%3A244fd47e07d10?repository_url=gcr.io/distroless/static&tag=latest">>,
                    <<"pkg:oci/hello-wasm@sha256:244fd47e07d10?tag=v1">>
                ],
            name_definition =>
                #{
                    case_sensitive => false,
                    note =>
                        <<"The name is not case sensitive and must be lowercased. The name is the last fragment of the repository name. For example if the repository name is library/debian then the name is debian.">>,
                    requirement => <<"required">>
                },
            namespace_definition =>
                #{
                    note =>
                        <<"OCI purls do not contain a namespace, although, repository_url may contain a namespace as part of the physical location of the package.">>,
                    requirement => <<"prohibited">>
                },
            qualifiers_definition =>
                [
                    #{
                        description => <<"key for a package architecture, when relevant.">>,
                        key => <<"arch">>
                    },
                    #{
                        description =>
                            <<"A repository URL where the artifact may be found, but not intended as the only location. This value is encouraged to identify a location the content may be fetched.">>,
                        key => <<"repository_url">>
                    },
                    #{
                        description =>
                            <<"artifact tag that may have been associated with the digest at the time.">>,
                        key => <<"tag">>
                    }
                ],
            reference_urls =>
                [<<"https://github.com/opencontainers/distribution-spec">>],
            repository =>
                #{
                    note =>
                        <<"There is no canonical package repository for OCI artifacts. Therefore oci purls must be registry agnostic by default. To specify the repository, provide a repository_url value.">>,
                    use_repository => true
                },
            type => <<"oci">>,
            type_name => <<"OCI image">>,
            version_definition =>
                #{
                    case_sensitive => false,
                    note =>
                        <<"The version is the sha256:hex_encoded_lowercase_digest of the artifact and is required to uniquely identify the artifact.">>,
                    requirement => <<"optional">>
                }
        },
        #{
            '$id' => <<"https://packageurl.org/types/opam-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description => <<"Opam packages">>,
            examples =>
                [<<"pkg:opam/ocaml-base-compiler@5.2.0">>, <<"pkg:opam/git@3/16.1">>],
            name_definition =>
                #{
                    case_sensitive => true,
                    native_name => <<"name">>,
                    note => <<"The name is case sensitive.">>,
                    requirement => <<"required">>
                },
            namespace_definition =>
                #{note => <<"there is no namespace">>, requirement => <<"prohibited">>},
            repository =>
                #{
                    default_repository_url => <<"https://opam.ocaml.org">>,
                    use_repository => true
                },
            type => <<"opam">>,
            type_name => <<"Opam package">>,
            version_definition =>
                #{
                    native_name => <<"version">>,
                    note => <<"The version is package version.">>,
                    requirement => <<"optional">>
                }
        },
        #{
            '$id' => <<"https://packageurl.org/types/otp-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description =>
                <<"BEAM/OTP applications written in Elixir, Erlang, Gleam and other BEAM languages">>,
            examples =>
                [
                    <<"pkg:otp/erts@10.6.3?platform=linux&arch=amd64&repository_url=https:%2F%2Fgithub.com%2Ferlang%2Fotp&vcs_url=git%2Bhttps:%2F%2Fgithub.com%2Ferlang%2Fotp.git">>,
                    <<"pkg:otp/stdlib@3.11.2?repository_url=https:%2F%2Fgithub.com%2Ferlang%2Fotp&vcs_url=git%2Bhttps:%2F%2Fgithub.com%2Ferlang%2Fotp.git">>,
                    <<"pkg:otp/crypto@4.6.4?platform=darwin&arch=x86_64&repository_url=https:%2F%2Fgithub.com%2Ferlang%2Fotp&vcs_url=git%2Bhttps:%2F%2Fgithub.com%2Ferlang%2Fotp.git">>,
                    <<"pkg:otp/elixir@1.10.0?repository_url=https:%2F%2Fgithub.com%2Felixir-lang%2Felixir&vcs_url=git%2Bhttps:%2F%2Fgithub.com%2Felixir-lang%2Felixir.git">>,
                    <<"pkg:otp/eex@1.10.0?repository_url=https:%2F%2Fgithub.com%2Felixir-lang%2Felixir&vcs_url=git%2Bhttps:%2F%2Fgithub.com%2Felixir-lang%2Felixir.git">>,
                    <<"pkg:otp/logger@1.10.0?repository_url=https:%2F%2Fgithub.com%2Felixir-lang%2Felixir&vcs_url=git%2Bhttps:%2F%2Fgithub.com%2Felixir-lang%2Felixir.git">>,
                    <<"pkg:otp/rebar@3.13.0?repository_url=https:%2F%2Fgithub.com%2Ferlang%2Frebar3&vcs_url=git%2Bhttps:%2F%2Fgithub.com%2Ferlang%2Frebar3.git">>,
                    <<"pkg:otp/hex@2.1.1?repository_url=https:%2F%2Fgithub.com%2Fhexpm%2Fhex&vcs_url=git%2Bhttps:%2F%2Fgithub.com%2Fhexpm%2Fhex.git">>
                ],
            name_definition =>
                #{
                    case_sensitive => false,
                    native_name => <<"name">>,
                    note =>
                        <<"The OTP application name from the `.app` file; it is case-insensitive and MUST be lower-cased.">>,
                    requirement => <<"required">>
                },
            namespace_definition =>
                #{
                    note => <<"The component is unused and MUST be empty">>,
                    requirement => <<"prohibited">>
                },
            note =>
                <<"- If the component was fetched from a Hex repository, prefer a ``hex`` purl\n  because Hex provides a global, collision-free namespace that uniquely ties\n  the version to the published source.\n- There is no default package repository. When the application can be\n  fetched from a known location, add a general qualifier such as\n  `repository_url`, `download_url` or `vcs_url`.">>,
            qualifiers_definition =>
                [
                    #{
                        description =>
                            <<"The canonical origin of the OTP application source. This qualifier is optional, but it should be included whenever the origin is known, and should point to a trusted source repository.">>,
                        key => <<"repository_url">>,
                        native_name => <<"Repository URL">>,
                        requirement => <<"optional">>
                    },
                    #{
                        description =>
                            <<"The target operating system for native code (e.g. ``linux``, ``darwin``, ``freebsd``, ``sunos``, ``win32``; case-insensitive).">>,
                        key => <<"platform">>,
                        native_name => <<"platform">>,
                        requirement => <<"optional">>
                    },
                    #{
                        description =>
                            <<"The arch is the qualifiers key for a package architecture.">>,
                        key => <<"arch">>,
                        native_name => <<"arch">>,
                        requirement => <<"optional">>
                    }
                ],
            repository => #{use_repository => false},
            subpath_definition =>
                #{
                    case_sensitive => false,
                    native_name =>
                        <<"May be added to reference a specific file or directory inside the OTP application.">>,
                    requirement => <<"optional">>
                },
            type => <<"otp">>,
            type_name => <<"BEAM/OTP Application">>,
            version_definition =>
                #{
                    native_name => <<"version">>,
                    note => <<"The OTP application version (the `vsn` attribute).">>,
                    requirement => <<"optional">>
                }
        },
        #{
            '$id' => <<"https://packageurl.org/types/pub-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description => <<"Dart and Flutter pub packages">>,
            examples => [<<"pkg:pub/characters@1.2.0">>, <<"pkg:pub/flutter@0.0.0">>],
            name_definition =>
                #{
                    case_sensitive => false,
                    native_name => <<"name">>,
                    normalization_rules =>
                        [<<"Replace non-[a-z] letters, non-[0-9] digits with underscore _">>],
                    note =>
                        <<"Pub normalizes all package names to be lowercase and using underscores. The only allowed characters are [a-z0-9_]. More information on pub naming and versioning is available in the pubspec documentation https://dart.dev/tools/pub/pubspec">>,
                    permitted_characters => <<"^[a-z0-9_]">>,
                    requirement => <<"required">>
                },
            namespace_definition =>
                #{note => <<"there is no namespace">>, requirement => <<"prohibited">>},
            repository =>
                #{
                    default_repository_url => <<"https://pub.dartlang.org">>,
                    use_repository => true
                },
            type => <<"pub">>,
            type_name => <<"Pub">>,
            version_definition =>
                #{native_name => <<"version">>, requirement => <<"optional">>}
        },
        #{
            '$id' => <<"https://packageurl.org/types/pypi-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description => <<"Python packages">>,
            examples =>
                [
                    <<"pkg:pypi/django@1.11.1">>,
                    <<"pkg:pypi/django@1.11.1?file_name=Django-1.11.1.tar.gz">>,
                    <<"pkg:pypi/django@1.11.1?file_name=Django-1.11.1-py2.py3-none-any.whl">>,
                    <<"pkg:pypi/django-allauth@12.23">>
                ],
            name_definition =>
                #{
                    case_sensitive => false,
                    native_name => <<"name">>,
                    normalization_rules =>
                        [
                            <<"Replace underscore _ with dash -">>,
                            <<"Replace dot . with underscore _ when used in distribution (sdist, wheel) names">>
                        ],
                    note =>
                        <<"PyPI treats - and _ as the same character and is not case sensitive. Therefore a PyPI package name must be lowercased and underscore _ replaced with a dash -. Note that PyPI itself is preserving the case of package names. When used in distribution and wheel names, the dot . is replaced with an underscore _">>,
                    requirement => <<"required">>
                },
            namespace_definition =>
                #{note => <<"there is no namespace">>, requirement => <<"prohibited">>},
            qualifiers_definition =>
                [
                    #{
                        description =>
                            <<"The file_name qualifier selects a particular distribution file (case-sensitive). For naming convention, see the Python Packaging User Guide on source distributions https://packaging.python.org/en/latest/specifications/source-distribution-format/#source-distribution-file-name and on binary distributions https://packaging.python.org/en/latest/specifications/binary-distribution-format/#file-name-convention and the rules for platform compatibility tags https://packaging.python.org/en/latest/specifications/platform-compatibility-tags/">>,
                        key => <<"file_name">>,
                        requirement => <<"optional">>
                    }
                ],
            repository =>
                #{
                    default_repository_url => <<"https://pypi.org">>,
                    note => <<"Previously https://pypi.python.org">>,
                    use_repository => true
                },
            type => <<"pypi">>,
            type_name => <<"PyPI">>,
            version_definition =>
                #{
                    case_sensitive => false,
                    native_name => <<"version">>,
                    requirement => <<"optional">>
                }
        },
        #{
            '$id' => <<"https://packageurl.org/types/qpkg-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description => <<"QNX packages">>,
            examples =>
                [
                    <<"pkg:qpkg/blackberry/com.qnx.sdp@7.0.0.SGA201702151847">>,
                    <<"pkg:qpkg/blackberry/com.qnx.qnx710.foo.bar.qux@0.0.4.01449T202205040833L">>
                ],
            name_definition =>
                #{native_name => <<"name">>, requirement => <<"required">>},
            namespace_definition =>
                #{
                    case_sensitive => false,
                    native_name => <<"vendor">>,
                    note =>
                        <<"The namespace is the vendor of the package. It is not case sensitive and must be lowercased.">>,
                    requirement => <<"required">>
                },
            repository =>
                #{
                    note =>
                        <<"There is no default package repository, this should be implied either from the namespace or using a repository base URL as repository_url qualifiers key.">>,
                    use_repository => true
                },
            type => <<"qpkg">>,
            type_name => <<"QNX package">>
        },
        #{
            '$id' => <<"https://packageurl.org/types/rpm-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description => <<"RPM packages">>,
            examples =>
                [
                    <<"pkg:rpm/fedora/curl@7.50.3-1.fc25?arch=i386&distro=fedora-25">>,
                    <<"pkg:rpm/centerim@4.22.10-1.el6?arch=i686&epoch=1&distro=fedora-25">>
                ],
            name_definition =>
                #{
                    case_sensitive => true,
                    native_name => <<"name">>,
                    note => <<"The name is the RPM name and is case sensitive.">>,
                    requirement => <<"required">>
                },
            namespace_definition =>
                #{
                    case_sensitive => false,
                    native_name => <<"vendor">>,
                    note =>
                        <<"The namespace is the vendor such as Fedora or OpenSUSE. It is not case sensitive and must be lowercased.">>,
                    requirement => <<"required">>
                },
            qualifiers_definition =>
                [
                    #{
                        description =>
                            <<"(optional for RPMs) is a qualifier as its not required for unique identification, but when the epoch exists we strongly encourage using it.">>,
                        key => <<"epoch">>,
                        requirement => <<"optional">>
                    },
                    #{
                        description => <<"the qualifiers key for a package architecture.">>,
                        key => <<"arch">>
                    }
                ],
            repository =>
                #{
                    note =>
                        <<"There is no default package repository, this should be implied either from the distro qualifiers key or using a repository base URL as repository_url qualifiers key.">>,
                    use_repository => true
                },
            type => <<"rpm">>,
            type_name => <<"RPM">>,
            version_definition =>
                #{
                    native_name => <<"version-release">>,
                    note =>
                        <<"The version is the combined version and release of an RPM.">>,
                    requirement => <<"optional">>
                }
        },
        #{
            '$id' => <<"https://packageurl.org/types/swid-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description =>
                <<"PURL type for ISO-IEC 19770-2 Software Identification (SWID) tags.">>,
            examples =>
                [
                    <<"pkg:swid/Acme/example.com/Enterprise+Server@1.0.0?tag_id=75b8c285-fa7b-485b-b199-4745e3004d0d">>,
                    <<"pkg:swid/Fedora@29?tag_id=org.fedoraproject.Fedora-29">>,
                    <<"pkg:swid/Adobe%2BSystems%2BIncorporated/Adobe%2BInDesign@CC?tag_id=CreativeCloud-CS6-Win-GM-MUL">>
                ],
            name_definition =>
                #{
                    case_sensitive => true,
                    native_name => <<"SoftwareIdentity/name">>,
                    note =>
                        <<"The name is the name as defined in the SWID SoftwareIdentity element.">>,
                    requirement => <<"required">>
                },
            namespace_definition =>
                #{
                    case_sensitive => true,
                    native_name => <<"softwareCreator">>,
                    note =>
                        <<"The namespace is the optional name and regid of the entity with a role of softwareCreator. If specified, name is required and is the first segment in the namespace. If regid is known, it must be specified as the second segment in the namespace. A maximum of two segments are supported.">>,
                    requirement => <<"optional">>
                },
            note =>
                <<"Use of known qualifiers key/value pairs such as download_url can be used to specify where the package was retrieved from.">>,
            qualifiers_definition =>
                [
                    #{
                        description =>
                            <<"The qualifier tag_id must not be empty and corresponds to the tagId as defined in the SWID SoftwareIdentity element. Per the SWID specification, GUIDs are recommended. If a GUID is used, it must be lowercase. If a GUID is not used, the tag_id qualifier is case aware but not case sensitive.">>,
                        key => <<"tag_id">>,
                        requirement => <<"required">>
                    },
                    #{
                        description =>
                            <<"The qualifier tag_version is an optional integer and corresponds to the tagVersion as defined in the SWID SoftwareIdentity element. If not specified, defaults to 0.">>,
                        key => <<"tag_version">>,
                        requirement => <<"optional">>
                    },
                    #{
                        description =>
                            <<"The qualifier patch is optional and corresponds to the patch as defined in the SWID SoftwareIdentity element. If not specified, defaults to false.">>,
                        key => <<"patch">>,
                        requirement => <<"optional">>
                    },
                    #{
                        description =>
                            <<"The qualifier tag_creator_name is optional. If the tag creator is different from the software creator, the tag_creator_name qualifier should be specified.">>,
                        key => <<"tag_creator_name">>,
                        requirement => <<"optional">>
                    },
                    #{
                        description =>
                            <<"The qualifier tag_creator_regid is optional. If the tag creator is different from the software creator, the tag_creator_regid qualifier should be specified.">>,
                        key => <<"tag_creator_regid">>,
                        requirement => <<"optional">>
                    }
                ],
            repository =>
                #{
                    note => <<"There is no default package repository.">>,
                    use_repository => false
                },
            type => <<"swid">>,
            type_name => <<"Software Identification (SWID) Tag">>,
            version_definition =>
                #{
                    case_sensitive => true,
                    native_name => <<"SoftwareIdentity/version">>,
                    note =>
                        <<"The version is the version as defined in the SWID SoftwareIdentity element.">>,
                    requirement => <<"optional">>
                }
        },
        #{
            '$id' => <<"https://packageurl.org/types/swift-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description => <<"Swift packages">>,
            examples =>
                [
                    <<"pkg:swift/github.com/Alamofire/Alamofire@5.4.3">>,
                    <<"pkg:swift/github.com/RxSwiftCommunity/RxFlow@2.12.4">>
                ],
            name_definition =>
                #{
                    case_sensitive => true,
                    native_name => <<"repository name">>,
                    requirement => <<"required">>
                },
            namespace_definition =>
                #{
                    case_sensitive => true,
                    note =>
                        <<"The namespace is source host and user/organization and is required.">>,
                    requirement => <<"required">>
                },
            repository =>
                #{
                    note =>
                        <<"There is no default package repository, this should be implied from namespace.">>,
                    use_repository => true
                },
            type => <<"swift">>,
            type_name => <<"Swift packages">>,
            version_definition =>
                #{
                    case_sensitive => true,
                    native_name => <<"package version">>,
                    requirement => <<"optional">>
                }
        },
        #{
            '$id' => <<"https://packageurl.org/types/vcpkg-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description => <<"Packages from the vcpkg C/C++ package manager.">>,
            examples =>
                [
                    <<"pkg:vcpkg/bzip2@1.0.8?port_version=6">>,
                    <<"pkg:vcpkg/ffmpeg@5.1.2?repository_url=https:%2F%2Fgithub.com%2Fazure-sdk%2Fvcpkg">>,
                    <<"pkg:vcpkg/llvm@15.0.7?repository_url=file:%2F%2F%2FC:%2Flocal-registry%2Fvcpkg">>,
                    <<"pkg:vcpkg/bzip2@1.0.8?port_version=6&repository_revision=84a143e4caf6b70db57f28d04c41df4a85c480fa&triplet=x64-linux">>
                ],
            name_definition =>
                #{
                    native_name => <<"package-name">>,
                    note => <<"The vcpkg package name.">>,
                    requirement => <<"required">>
                },
            namespace_definition => #{requirement => <<"prohibited">>},
            note =>
                <<"A purl may carry extra qualifiers that describe the context in which the package is used, such as build configuration or platform. Parsers must tolerate these and may ignore any they do not expect. The `features` qualifier, a comma-separated list of enabled vcpkg feature names, records which optional features were enabled at build time; it is informational and not currently normative.">>,
            qualifiers_definition =>
                [
                    #{
                        description =>
                            <<"The vcpkg [port-version](https://learn.microsoft.com/vcpkg/reference/vcpkg-json#port-version). If omitted, the purl refers to port-version 0.">>,
                        key => <<"port_version">>,
                        native_name => <<"port_version">>,
                        requirement => <<"optional">>
                    },
                    #{
                        description =>
                            <<"The full 40-character commit hash of the vcpkg registry. For git registries this corresponds to the registry `baseline` field in `vcpkg-configuration.json`. If omitted, the purl refers to the latest revision available.">>,
                        key => <<"repository_revision">>,
                        native_name => <<"repository_revision">>,
                        requirement => <<"optional">>
                    },
                    #{
                        description =>
                            <<"The vcpkg [triplet](https://learn.microsoft.com/vcpkg/concepts/triplets) describing the target build configuration (architecture, operating system, and CRT/library linkage), for example `x64-windows` or `arm64-osx`. It describes the build target and does not affect package identity.">>,
                        key => <<"triplet">>,
                        native_name => <<"triplet">>,
                        requirement => <<"optional">>
                    }
                ],
            repository =>
                #{
                    default_repository_url => <<"https://github.com/microsoft/vcpkg/">>,
                    note =>
                        <<"The absolute URL of the vcpkg registry where the package is available. If omitted, the default registry `https://github.com/microsoft/vcpkg` is assumed. For filesystem registries or [overlay ports](https://learn.microsoft.com/vcpkg/concepts/overlay-ports), the URL uses the `file` scheme.">>,
                    use_repository => true
                },
            type => <<"vcpkg">>,
            type_name => <<"Vcpkg C/C++ packages">>,
            version_definition =>
                #{
                    native_name => <<"package-version">>,
                    note => <<"The vcpkg package version.">>,
                    requirement => <<"optional">>
                }
        },
        #{
            '$id' => <<"https://packageurl.org/types/vscode-extension-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description => <<"VS Code Extension packages">>,
            examples =>
                [
                    <<"pkg:vscode-extension/ms-python/python@2023.25.10292213">>,
                    <<"pkg:vscode-extension/muhammad-sammy/csharp@2.15.30?repository_url=https://open-vsx.org">>,
                    <<"pkg:vscode-extension/golang/go@0.39.1?platform=win32-x64">>
                ],
            name_definition =>
                #{
                    case_sensitive => false,
                    native_name => <<"name">>,
                    note =>
                        <<"The extension name. This corresponds to the 'Id' property of the 'Identity' element in the package's .vsixmanifest file.">>,
                    requirement => <<"required">>
                },
            namespace_definition =>
                #{
                    case_sensitive => false,
                    native_name => <<"publisher">>,
                    note =>
                        <<"The namespace is the publisher or vendor of the extension (e.g., 'redhat', 'microsoft'). This corresponds to the 'Publisher' property of the 'Identity' element in the package's .vsixmanifest file.">>,
                    requirement => <<"required">>
                },
            qualifiers_definition =>
                [
                    #{
                        default_value => <<"universal">>,
                        description =>
                            <<"The target platform for the extension. Common values include 'universal', 'linux-x64', 'linux-arm64', 'darwin-x64', 'darwin-arm64', 'win32-x64', 'win32-arm64', etc.">>,
                        key => <<"platform">>,
                        native_name => <<"targetPlatform">>,
                        requirement => <<"optional">>
                    }
                ],
            reference_urls =>
                [
                    <<"https://open-vsx.org/">>,
                    <<"https://github.com/eclipse/openvsx">>,
                    <<"https://code.visualstudio.com/api/working-with-extensions/publishing-extension#platformspecific-extensions">>
                ],
            repository =>
                #{
                    default_repository_url =>
                        <<"https://marketplace.visualstudio.com/vscode-extension">>,
                    use_repository => true
                },
            type => <<"vscode-extension">>,
            type_name => <<"VS Code Extension packages">>,
            version_definition =>
                #{
                    case_sensitive => false,
                    native_name => <<"version">>,
                    note =>
                        <<"The extension version. This corresponds to the 'Version' property of the 'Identity' element in the package's .vsixmanifest file.">>,
                    requirement => <<"optional">>
                }
        },
        #{
            '$id' => <<"https://packageurl.org/types/yocto-definition.json">>,
            '$schema' =>
                <<"https://packageurl.org/schemas/purl-type-definition.schema-1.0.json">>,
            description => <<"Yocto Project recipes">>,
            examples =>
                [
                    <<"pkg:yocto/core/glibc@2.35">>,
                    <<"pkg:yocto/core/glibc@2.35&repository_url=https:%2F%2Fgit.openembedded.org%2Fopenembedded-core&layer_version=kirkstone">>,
                    <<"pkg:yocto/core/glibc@2.35&repository_url=https:%2F%2Fgit.openembedded.org%2Fopenembedded-core&layer_version=25ba9895b9">>,
                    <<"pkg:yocto/core/glibc@2.35&repository_url=https:%2F%2Fgit.openembedded.org%2Fopenembedded-core&layer_version=25ba9895b98715adb66a06e50f644aea2e2c9eb6">>,
                    <<"pkg:yocto/xilinx/u-boot-xlnx-uenv@1.0.0">>,
                    <<"pkg:yocto/odroid-layer/emmc@1.0.0?layer_version=4e07fab&repository_url=https:%2F%2Fgithub.com%2Fakuster%2Fmeta-odroid">>
                ],
            name_definition =>
                #{
                    case_sensitive => true,
                    native_name => <<"BPN">>,
                    note =>
                        <<"The name of the package with common prefixes and suffixes removed, also known as BPN (https://docs.yoctoproject.org/ref-manual/variables.html#term-BPN) in a yocto recipe.">>,
                    requirement => <<"required">>
                },
            namespace_definition =>
                #{
                    case_sensitive => false,
                    native_name => <<"layer">>,
                    note =>
                        <<"The namespace is the name of the layer which provides the recipe. The layer name as specified in the BBFILE_COLLECTIONS variable in conf/layer.conf of the layer.">>,
                    requirement => <<"optional">>
                },
            qualifiers_definition =>
                [
                    #{
                        description =>
                            <<"The GIT URL of the layer. In example: https:%2F%2Fgit.openembedded.org%2Fopenembedded-core or https:%2F%2Fgithub.com%2Fakuster%2Fmeta-odroid. The URL scheme is mandatory and must be one of https, http, ssh, or git.">>,
                        key => <<"repository_url">>,
                        requirement => <<"optional">>
                    },
                    #{
                        description =>
                            <<"layer_version is the version of the yocto layer which is a SHA1 commit, tag or branch of the yocto layer GIT repository. It should support also short commits (https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection#_short_sha_1).">>,
                        key => <<"layer_version">>,
                        requirement => <<"optional">>
                    }
                ],
            repository =>
                #{
                    note =>
                        <<"There is no default package repository. The classifier repository_url is optional.">>,
                    use_repository => true
                },
            type => <<"yocto">>,
            type_name => <<"Yocto Project">>,
            version_definition =>
                #{
                    native_name => <<"PV">>,
                    note =>
                        <<"The version of the package also known as PV (https://docs.yoctoproject.org/ref-manual/variables.html#term-PV>) in a yocto recipe.">>,
                    requirement => <<"optional">>
                }
        }
    ].
