on:
  push:
    branches:
      - "main"

name: "Main Branch"

jobs:
  test:
    name: "Test"

    uses: ./.github/workflows/part_test.yml

  docs:
    name: "Docs"

    uses: ./.github/workflows/part_docs.yml

  dependency_submission:
    name: "Mix Dependency Submission"

    permissions:
      contents: write

    uses: ./.github/workflows/part_dependency_submission.yml
