on:
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}

name: "Pull Request"

jobs:
  test:
    name: "Test"

    uses: ./.github/workflows/part_test.yml

  docs:
    name: "Docs"

    uses: ./.github/workflows/part_docs.yml

  dependency_review:
    name: "Dependency Review"

    uses: ./.github/workflows/part_dependency_review.yml
