on:
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}

name: "Pull Request"

jobs:
  test:
    name: "Test"

    uses: ./.github/workflows/part_test.yml
    with:
      elixirVersion: "1.14.3"
      otpVersion: "25.3"

  docs:
    name: "Docs"

    uses: ./.github/workflows/part_docs.yml
    with:
      elixirVersion: "1.14.3"
      otpVersion: "25.3"

  dependabot:
    name: "Dependabot"

    needs: ["test", "docs"]

    uses: ./.github/workflows/part_dependabot.yml
