on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

name: "Stable Tag"

permissions:
  contents: read

jobs:
  docs:
    name: "Docs"

    permissions:
      id-token: write
      contents: read
      attestations: write

    uses: ./.github/workflows/part_docs.yml

  publish:
    name: "Publish"

    uses: ./.github/workflows/part_publish.yml
    with:
      releaseName: "${{ github.ref_name }}"
    secrets:
      HEX_API_KEY: "${{ secrets.HEX_API_KEY }}"

  release:
    name: "Release"

    needs: ["docs"]

    permissions:
      contents: write

    uses: ./.github/workflows/part_release.yml
    with:
      releaseName: "${{ github.ref_name }}"
      stable: true
